"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-center"
          toastOptions={{
            classNames: {
              // base style for all toasts
              toast: "!border !p-4 !rounded",
              description: "!text-sm",
              actionButton: "!bg-white !text-black !hover:bg-gray-200",
            },
            // style for success toasts
            success: {
              className: "!bg-green-600 !text-white !border-green-700",
            },
            // style for error toasts
            error: {
              className: "!bg-red-600 !text-white !border-red-700",
            },
          }}
        />

      </body>
    </html>
  );
}
